name: Actualizar Servicios Consulares

on:
  schedule:
    # Cron job para ejecutarse antes de las 2:00 cada lunes. La hora está en UTC.
    # - cron: '43 1 * * 1'
    - cron: '10 8-23 * * *'
  workflow_dispatch: # Permite la ejecución manual del workflow

jobs:
  actualizar-contenidos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3
      with:
        ref: develop # Asegúrate de hacer checkout de la rama correcta

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Asegúrate de usar la versión de Python que necesites

    - name: Instalar dependencias
      run: |
        python -m venv venv # Crea un entorno virtual
        source venv/bin/activate # Activa el entorno virtual
        pip install -r requirements.txt

    - name: Ejecutar script de scraping
      run: |
        source venv/bin/activate # Activa el entorno virtual
        python consulate_content_scraper.py
      
      # python download-servicios-consulares.py

    - name: Añadir cambios al staging
      run: git add .

    - name: Commit cambios
      run: git diff --quiet || git commit -m "Cambio en contenidos"

    - name: Push al origen
      run: git push origin develop
